export { Home as PageHome } from "./Home"
export { Menu as PageMenu } from "./Menu"
export { Layout as PageLayout } from "./Layout"
export { Login as PageLogin } from "./Login"
export { Cadastrar as PageCadastrar } from "./Cadastrar"
export { Adm as PageAdm } from "./Adm"
